(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function b(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=b(t);fetch(t.href,n)}})();const A=document.querySelector(".team__list"),y=document.querySelectorAll(".team__item"),w=document.querySelector(".team__btn-left"),x=document.querySelector(".team__btn-right");let s=0;window.addEventListener("keydown",a=>{a.key==="ArrowRight"&&s<y.length-1&&(s+=1,u(),s===y.length&&(s=0,u(),console.log(s),console.log(y.length),console.log("hello"))),a.key==="ArrowLeft"&&s>0&&(s-=1,u())});x.addEventListener("click",()=>{s<y.length-1&&(s+=1,u())});w.addEventListener("click",()=>{s>0&&(s-=1,u())});function u(){const a=-s*100;A.style.transform=`translateX(${a}%)`}const r=[{name:"Albert",surname:"Einstein",born:1879,dead:1955,id:1},{name:"Isaac",surname:"Newton",born:1643,dead:1727,id:2},{name:"Galileo",surname:"Galilei",born:1564,dead:1642,id:3},{name:"Marie",surname:"Curie",born:1867,dead:1934,id:4},{name:"Johannes",surname:"Kepler",born:1571,dead:1630,id:5},{name:"Nicolaus",surname:"Copernicus",born:1473,dead:1543,id:6},{name:"Max",surname:"Planck",born:1858,dead:1947,id:7},{name:"Katherine",surname:"Blodgett",born:1898,dead:1979,id:8},{name:"Ada",surname:"Lovelace",born:1815,dead:1852,id:9},{name:"Sarah E.",surname:"Goode",born:1855,dead:1905,id:10},{name:"Lise",surname:"Meitner",born:1878,dead:1968,id:11},{name:"Hanna",surname:"Hammarström",born:1829,dead:1909,id:12}],E=document.querySelector(".scientists__sortedList"),R=document.querySelectorAll(".scientists__desc");function o(a){const l=a.map(({name:i,surname:t,born:n,dead:c})=>`
        <li class="scientists__box">
        <div class="scientists__boxes">
  <h2 class="scientists__name">${i}</h2>
  <h3 class="scientists__name">${t}</h3>
  </div>
  <div class="scientists__wrap">
  <p>${n}</p>
  <p>-${c}</p>
</div>
</li>`).join("");E.innerHTML=l,E.querySelectorAll(".scientists__box").forEach(i=>{setTimeout(()=>i.classList.add("show"),50)})}R.forEach(a=>{a.addEventListener("click",l=>{switch(l.currentTarget.dataset.id){case"scientistsBorn19c":const i=r.filter(({born:e})=>e>=1800&&e<1900);o(i);break;case"sortByAlphabet":const t=[...r].sort((e,d)=>e.name.localeCompare(d.name));o(t);break;case"sortByYears":const n=[...r].sort((e,d)=>{const k=e.dead-e.born,q=d.dead-d.born;return k-q});o(n);break;case"latestBirth":let c=r[0].born;r.forEach(e=>{e.born>c&&(c=e)}),o([c]);break;case"findByFirstLetters":const S=r.filter(e=>e.name[0]===e.surname[0]);o(S);break;case"AlbertEinsteinBirth":const L=r.find(e=>e.name==="Albert");L&&o([L]);break;case"surnameByC":const g=r.filter(e=>e.surname[0]==="C");o(g);break;case"deleteByA":const B=r.filter(e=>e.name[0]!=="A");o(B);break;case"findLongestAndShortestLife":let m=r[0],f=r[0];r.forEach(e=>{let d=e.dead-e.born;d>m.dead-m.born&&(m=e),d<f.dead-f.born&&(f=e)}),o([f,m]);break}})});o(r);const h=document.querySelector(".modal1"),O=document.querySelector(".modal_close_btn"),C=document.querySelector(".temperaryOpenBtn"),N=document.querySelector(".temperaryTextUser"),p=document.querySelector(".your_name"),M=document.querySelector(".save_name_btn");C.addEventListener("click",()=>{h.style.display="block"});O.addEventListener("click",()=>{h.style.display="none"});M.addEventListener("click",()=>{if(p.value==""){p.classList.add("your_name_wrong");return}N.textContent=p.value,h.style.display="none"});const v=document.querySelector(".modal2"),$=document.querySelector(".modal2_close_btn"),P=document.querySelector(".temperaryOpenBtn2");P.addEventListener("click",()=>{v.style.display="block"});$.addEventListener("click",()=>{v.style.display="none"});const T=document.querySelector(".modal2"),_=document.querySelector(".footer__input"),F=document.querySelector(".footer__btn");F.addEventListener("click",()=>{_.value!==""&&_.value.includes("@")&&(T.style.display="block"),_.value=""});
//# sourceMappingURL=commonHelpers.js.map
